CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT_DATETIME);
CREATE TABLE IF NOT EXISTS "soju_jobs" ("id" BLOB NOT NULL PRIMARY KEY, "worker" TEXT NOT NULL, "status" INTEGER DEFAULT 0 NOT NULL, "errors" JSON DEFAULT '[]' NOT NULL, "attempts" INTEGER DEFAULT 0 NOT NULL, "scheduled_at" TEXT_DATETIME NOT NULL, "args" JSON NOT NULL);
INSERT INTO schema_migrations VALUES(20220712221106,'2022-07-12T22:21:39');
